DAY 1

In [ ]:
## Swap two numbers
# a= int(input("Enter first number (a) : - "))
# b= int(input("Enter second number (b) : - "))
# a,b = b,a
# print(" After swapping a = ", a)
# print(" After swapping b = ", b)

In [ ]:

## Sum of list

# lst = [3,7,2,9,2]
# sum = 0
# for i in lst:
#     sum += i

In [ ]:
## Find Maximum number in a list

# lst = [23,12,17,28,96,36,75,105]
# max_lst = lst[0]
# for i in lst:
#     if i>max_lst:
#         max_lst = i
# print(max_lst)

In [ ]:
## Reverse a string

# str = input("Enter any word : - ")
# print("Reversed String is : -", str[::-1])

## Factorial of number using function

In [ ]:

# def fact(num):
#     if num == 0:
#         return 1
#     return num*fact(num-1)

# print(fact(3))

============= HOUR 4: NUMPY==================

In [6]:
### --------------- 1D Array-----------------
import numpy as np
arr1 = np.array([25,87,89,36,24])
print(arr1)
print(type(arr1))

[25 87 89 36 24]
<class 'numpy.ndarray'>

In [9]:
## 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(type(arr2))
arr2.shape

<class 'numpy.ndarray'>

(2, 3)

In [ ]:
###--------- Zeros array-----------
# arr3 = np.zeros((2,3))
# print(arr3)

# arr4 = np.ones((3,2))
# arr4

# arr5 = np.full((2,2),7)
# arr5

# arr5 = np.ones((3,2))
# arr5

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#### arange

# a1 = np.arange(0,10,2)
# # a1

# print(a1*2)

# a2 = np.arange(6).reshape(2,3)
# a2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# a1= np.arange(1,7).reshape(2,3)
# a2 = np.arange(7,13).reshape(2,3)

#print(a1,a2,a1+a2,a1*a2)

[[1 2 3]
 [4 5 6]] [[ 7  8  9]
 [10 11 12]] [[ 8 10 12]
 [14 16 18]] [[ 7 16 27]
 [40 55 72]]

In [35]:
#### INDEXING

a1 = np.arange(1,10).reshape(3,3,1)
print(a1)
print(a1[0][1])

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
[2]

# ======= PANDAS ========

In [40]:
import pandas as pd

df = pd.read_csv("mobile_price_dataset.csv")
print(df.head())
# print(df.info())
df.describe()

     Brand          Model  Price_USD  RAM_GB  Storage_GB  Battery_mAh  \
0  Samsung     Galaxy S21        799       8         128         4000
1    Apple      iPhone 13        999       4         128         3240
2   Xiaomi  Redmi Note 11        199       6         128         5000
3   Realme   Realme 9 Pro        299       8         128         5000
4  OnePlus      OnePlus 9        729       8         128         4500

   Screen_Size_Inch  Camera_MP       OS  Release_Year
0              6.20         64  Android          2021
1              6.10         12      iOS          2021
2              6.43         50  Android          2022
3              6.60         64  Android          2022
4              6.55         48  Android          2021

,Price_USD,RAM_GB,Storage_GB,Battery_mAh,Screen_Size_Inch,Camera_MP,Release_Year
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,441.000000,6.266667,123.733333,4464.333333,6.472667,49.400000,2021.066667
std,277.004384,1.667619,45.038819,706.391400,0.204955,24.523458,0.593617
min,199.000000,4.000000,64.000000,2815.000000,6.100000,12.000000,2020.000000
25%,234.000000,5.000000,128.000000,4100.000000,6.415000,48.000000,2021.000000
50%,299.000000,6.000000,128.000000,4500.000000,6.510000,48.000000,2021.000000
75%,614.000000,8.000000,128.000000,5000.000000,6.600000,64.000000,2021.000000
max,999.000000,8.000000,256.000000,5160.000000,6.800000,108.000000,2022.000000

In [42]:
df.shape
df.columns

Index(['Brand', 'Model', 'Price_USD', 'RAM_GB', 'Storage_GB', 'Battery_mAh',
       'Screen_Size_Inch', 'Camera_MP', 'OS', 'Release_Year'],
      dtype='object')

In [ ]:
## Problem: Two Sum
## Given:
# list of numbers
# a target
# Find:
# indices of two numbers whose sum = target

def two_sums(nums,target):
    dct= {}
    for i, num in enumerate(nums):
        if target-num in dct:
            return dct[target-num],i
        dct[num] = i

print(two_sums([2,7,11,15],18))

(1, 2)

In [57]:
## Telco Churn Analysis

import pandas as pd
df = pd.read_csv("Telco_Customer_Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [59]:
df.columns
# customerID is identifier
# monthly charges, tenure, total charges are numerical
# Churn is the target 
# Partner, dependent, phone service are categorical
#

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')